pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                echo "📥 Cloning repository..."
                git branch: 'main', url: 'https://github.com/iddhawan01/Jenkinsfile-from-SCM.git'
                echo "✅ Clone completed!"
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    echo "🐳 Starting Docker Build..."
                    cd 03-Clone-And-DockerBuild-Jenkinsfile
                    docker build -t my-first-image .
                '''
            }
        }
    }

    post {
        success {
            echo "🎉 Docker image built successfully (Use Case)"
        }
        failure {
            echo "❌ Build failed — check logs."
        }
    }
}
